### ISSUE TITLE
When I see the image in reverse order, it does not display that image on which i hover the mouse

### ISSUE THREAD

**Issue by talhavbase** [wenzi0github/bzoom#1]
I liked your plugin.
Greate work.
But there is an issue in the plugin.
When i see the image in reverse order, it does not display that image on which i hover the mouse.
Ref.
http://www.jqueryscript.net/demo/jQuery-Plugin-For-Product-Viewer-with-Image-Hover-Zoom-BZoom/

**Comment by wenzi0github** [comment]
@talhavbase i have fixed this bug. This bug is caused because of `animate`. so i change the code queue, you can try it again.

**Comment by talhavbase** [comment]
Dear @wenzi0github ! Thank you for taking care and providing quick response. I downloaded plugin and ran your demo in 'index.html' but it is not showing in magnifier area.

**Comment by wenzi0github** [comment]
@talhavbase sorry,so late to modify this bug. I have changed agagin, it can no question.

**Comment by talhavbase** [comment]
@wenzi0github , now working fine.

But what if we need three image sizes for one,
one for thumb, one for zoomed area and one for upper main thumb image.
